### ISSUE TITLE
The y in get_sbfl_scores_from_frame funtion

### ISSUE THREAD

**Issue by Funoo** [Suresoft-GLaDOS/SBFL#17]
I've read the source code of the project. When I am trying to figure out the meaning of the y of the `get_sbfl_scores_from_frame` funtion, I found the `y` is just the result of whether the `failing_test` list was included in the data columns. I wondering why the y was calculated by this way. In my opinion, the y should be the test result. The way to calculate y seems to be irrational. Could you explain why you do it in this way? Thanks a lot.

```python
def get_sbfl_scores_from_frame(cov_df, failing_tests, sbfl=None):
    """
    Calculates sbfl scores from the coverage-matrix dataframe `cov_df` and `failing_tests`

    Parameters
    ----------
    cov_df : pd.Dataframe
        a pandas DataFrame format coverage matrix
        index: source, line number (two-level)
        column: test case name
    failing_tests: Iterable (set or list)
        a list/set of failing test names 
    sbfl: SBFL, optional
        SBFL-type instance
    
    Returns
    -------
    pd.Dataframe
        a pandas dataframe representing the SBFL scores
        that has only one column, score
    """

    assert all([t in cov_df.columns for t in failing_tests])
    X, y = cov_df.values.T > 0, ~cov_df.columns.isin(failing_tests) # why y is calculated by this
    if sbfl is None:
        sbfl = base.SBFL()
    sbfl.fit(X, y)
    return sbfl.to_frame(index=cov_df.index)
```

**Comment by agb94** [comment]
`A.isin(B)` checks whether **each element** in `A` is contained in `B` or not.
For example, if `cov_df.columns = [ A B C D ]` and `failing_tests = [ B ]`, 
then `cov_df.columns.isin(failing_tests)` is `[ False True False False ]`,
and, consequently, `~cov_df.columns.isin(failing_tests)` is `[ True False True True ]`,
Thus, `y` represents the test results (passing: True, failing: False).

**Comment by Funoo** [comment]
To sum up the source code and the above comment, do you mean `[A B C D]` in  `cov_df.columns = [ A B C D ]` are all failed testing case?

**Comment by agb94** [comment]
No, only `B` is a failing test.
To clarify:
- `cov_df.columns` contains the names of all test cases.
- The parameter `failing_tests` contains the list of failing test cases.
- `y` represents whether each test case in `cov_df.columns` is contained in `failing_tests` or not.

**Comment by agb94** [comment]
The file `main.ipynb` in the project root contains the example usage of `get_sbfl_scores_from_frame`. Hope it helps!

**Comment by Funoo** [comment]
Thank you for your instant replied. Yes, I've read the example of `get_sbfl_scores_from_frame` in file `main.ipynb`. I knew `y` represents whether each test case in `cov_df.columns` is contained in `failing_tests` or not. Now I want to figure out how do I get the value of the parameter `failing_tests`, or `failing_tests` can be selected by myself?

**Comment by agb94** [comment]
The latter one is correct.
Users should provide `failing_tests` based on test results.

**Comment by Funoo** [comment]
Thanks a lot. So the `'test102': 'resources/yara-buggy#3-102'` is a failing test dataset?
